name: Rust
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  clippy:
    name: Clippy
    runs-on: arc-runner-set-k8s
    container: ${{ vars.RUNNER_IMAGE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Clippy
        run: |
          echo "https://pyxis.nymag.com/v1/imgs/6fa/06a/f29f0541b8cab85631e2d4c2e10d690511-31-clippy.rsquare.w400.jpg"
